# Generated by Django 5.2.9 on 2026-07-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='username',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
