# Generated by Django 6.0.7 on 2026-07-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='WallOfText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=4000)),
            ],
        ),
    ]
